### ISSUE TITLE
Error trying: npm run generate

### ISSUE THREAD

**Issue by FutureQueenBee** [Kipwisp/vocal#5]
> vocal@1.0.0 generate
> node src/generate_codes.js

/home/pi/pythia/vocal/src/generate_codes.js:20
    get = bent(`https://15.ai${sourceCode[0]}`, 'GET', 'string', {
                                         ^

TypeError: Cannot read property '0' of null
    at getSourceFile (/home/pi/pythia/vocal/src/generate_codes.js:20:42)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async extractResources (/home/pi/pythia/vocal/src/generate_codes.js:31:20)
    at async generateCodes (/home/pi/pythia/vocal/src/generate_codes.js:77:45)
    at async writeCodes (/home/pi/pythia/vocal/src/generate_codes.js:118:28)
npm ERR! code 1
npm ERR! path /home/pi/pythia/vocal
npm ERR! command failed
npm ERR! command sh -c node src/generate_codes.js

**Comment by Kipwisp** [comment]
This bot is currently nonfunctional as 15.ai is down. The 'generate' script will now notify the user for when this is the case. Try again when 15.ai is back up.
